version: "3"

services:
  webserver:
    build: ./nginx
    container_name: webserver
    ports:
      - 8080:80
    depends_on:
      - dart
  dart:
    build: ./server
    container_name: dart-server